#!/bin/sh

set -e # exit if any command fails

dir=$(cd $(dirname $0); pwd)

# Work in this dir
cd $dir

touch 'update.lock'

./update-repo

./remove-old-builds

./list-branches | xargs -n 1 ./build-branch

(cd 'repo' && git checkout -q 'empty')

rm 'update.lock'
